update_each = "6h"
directory = "/tmp"
precision = "country"
host = "0.0.0.0"
port = 8000

[databases]

  [databases.ip2location]
  enabled = true
  weight = 1.0

  [databases.dbip]
  enabled = true
  weight = 1.1

  [databases.maxmind]
  enabled = true
  weight = 1.3

  [databases.sypex]
  enabled = true
  weight = 0.9
