[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  name = "github.com/oschwald/geoip2-golang"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/ip2location/ip2location-go"

[[constraint]]
  name = "gopkg.in/night-codes/go-sypexgeo.v1"
  version = "1.2.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/EvilSuperstars/go-cidrman"

[[constraint]]
  branch = "master"
  name = "github.com/asergeyev/nradix"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/xrash/smetrics"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
